language: php

sudo: false

matrix:
  fast_finish: false
  include:
    # Minimal versions according to https://wordpress.org/plugins/woocommerce-gateway-stripe/
    # TODO: debug; uncomment this once clear what minimal versions are
    # - php: 5.6
    #  env: WP_VERSION=4.6 WC_VERSION=3.9.3
    #  stage: test
    # passes at WP 4.7 and higher; the following builds will indicate min WC compatibility
    - php: 7.0
      env: WP_VERSION=4.8 WC_VERSION=3.9.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.9.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.8.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.7.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.6.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.5.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.4.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.3.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.2.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.1.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.8 WC_VERSION=3.1.0
      stage: test
    # breaks at WP 4.7; bot following builds must fail
    - php: 7.0
      env: WP_VERSION=4.7 WC_VERSION=3.9.0
      stage: test
    - php: 5.6
      env: WP_VERSION=4.7 WC_VERSION=3.9.0
      stage: test
    # WC version according to https://wordpress.org/plugins/woocommerce-gateway-stripe/
    # TODO:here should be latest and not 4.7.0
    # - php: 7.0
    #  env: WP_VERSION=latest WC_VERSION=4.7.0
    #  stage: test
    #- php: 7.1
    #  env: WP_VERSION=latest WC_VERSION=4.7.0
    #  stage: test
    # TODO: 7.2-7.4 to be added
    # PHP8 build environment
    # - php: nightly
    #  env: WP_VERSION=nightly WC_VERSION=nightly
    #  stage: test

services:
  - mysql

before_script:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
      echo "downloading phpunit 5 and rename to phpunit.phar"
      wget https://phar.phpunit.de/phpunit-5.7.27.phar && mv phpunit-5.7.27.phar phpunit.phar
    fi
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      echo "downloading phpunit 6 and rename to phpunit.phar"
      wget https://phar.phpunit.de/phpunit-6.5.14.phar && mv phpunit-6.5.14.phar phpunit.phar
    fi
  - phpenv config-rm xdebug.ini
  - bash tests/bin/install.sh wc_stripe_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - composer self-update 2.0.6
  - php --version && composer install --no-progress
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" || ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      php phpunit.phar -c phpunit.xml
    else
      ./vendor/bin/phpunit
    fi

#save node_modules to speed up build
cache:
  directories:
    - node_modules

after_script:
  - bash tests/bin/travis.sh after
